name: Publish alpha version
on:
  push:
    branches:
      - alpha
  repository_dispatch:
    types:
      - trigger-publish-alpha

jobs:
  build:
    name: Build and Publish to Test PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Lint with flake8
        run: make NO_VENV=True

      - name: Build test packages
        run: |
          export VERSION=`TZ="Europe/Kiev" date +%Y%m%d.%H%M`
          export RELEASE_DATE=`TZ="Europe/Kiev" date +%Y-%m-%d`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_DATE=RELEASE_DATE" >> $GITHUB_ENV
          make build NO_VENV=True ALPHA_VERSION=$VERSION

      - name: Upload math result for job 2
        uses: actions/upload-artifact@v1
        with:
          name: prana_rc.whl
          path: dist/prana_rc-${{ env.VERSION }}-py3-none-any.whl

      - name: Publish packages
        run: make publish NO_VENV=True PYPI_REPOSITORY_URL=https://test.pypi.org/legacy/ PYPI_API_KEY=${{ secrets.pypi_test_password }}

      # Docker build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./local.Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          build-args: |
            prana_version=${{ env.VERSION }}
            release_date=${{ env.RELEASE_DATE }}
            is_beta=True
          tags: |
            corvis/prana-rc:alpha