name: Build docker images
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be assigned for this release'

jobs:
  run:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Version from workflow event
        if: github.event.inputs.version != null
        run: |
          VERSION=${{ github.event.inputs.version }}
          export RELEASE_DATE=`TZ="Europe/Kiev" date +%Y-%m-%d`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: 'refs/heads/${{ env.VERSION }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
#          platforms: linux/amd64,linux/arm/v6,linux/arm/v7
          platforms: linux/amd64,linux/arm/v7
          push: true
          build-args: |
            prana_version=${{ env.VERSION }}
            release_date=${{ env.RELEASE_DATE }}
            is_beta=True
          tags: |
            corvis/prana-rc:latest