name: Update Changelog

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  run:
    name: Update Unreleased Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

    - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      id: generate_changelog
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        unreleasedOnly: true
        github_username: corvis
        issues: true

    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: UNRELEASED_CHANGELOG.MD
        contents: ${{ steps.generate_changelog.outputs.changelog }}
        write-mode: overwrite

    - run: |
        echo ${{ steps.generate_changelog.outputs.changelog }}


#    - name: Commit changelog
#      uses: EndBug/add-and-commit@v5
#      with:
#        author_name: Github Bot
#        author_email: github@bot.com
#        message: "Updated unreleased changelog"
#        add: "UNRELEASED_CHANGELOG.MD"
#        push: true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}